#' @export
load_estimates <- function(path,
                           decisions_and_options,
                           criteria) {

  if (!(all(c("dmcda", "decisions_and_options") %in%
            class(decisions_and_options)))) {
    stop("What you pass as 'instruments_and_options' needs to be an object as ",
         "generated by a call to the `load_decisions` function (which has ",
         "classes 'dmcda' and 'decisions_and_options', but you ",
         "passed an object of class ",
         ufs::vecTxtQ(class(decisions_and_options)), ".");
  }
  if (!(all(c("dmcda", "criteria") %in%
            class(criteria)))) {
    stop("What you pass as 'instruments_and_options' needs to be an object as ",
         "generated by a call to the `load_outcomes` function (which has ",
         "classes 'dmcda' and 'criteria', but you ",
         "passed an object of class ",
         ufs::vecTxtQ(class(criteria)), ".");
  }

  decisionsDf <-
    decisions_and_options$decisionsDf;
  optionsDf <-
    decisions_and_options$optionsDf;
  criteriaDf <-
    criteria$criteriaDf;

  ### Use suppressWarnings because we do not need identifiers
  suppressWarnings(
    estimates_raw <-
      justifier::load_justifications_dir(path)
  );

  ### Get all estimates
  estimates <-
    lapply(estimates_raw$supplemented$justifications,
           function(x) {
             if (!is.null(x$type) && x$type == "estimate") {
               return(x);
             } else {
               return(NULL);
             }
           });

  ### Get all assertions and sources
  assertions <-
    estimates_raw$supplemented$assertions;
  sources <-
    estimates_raw$supplemented$sources;

  ### Remove NULL elements
  estimates <-
    estimates[!unlist(lapply(estimates, is.null))];

  estimatesDf <-
    do.call(rbind,
            lapply(estimates,
                   function(x) {
                     decision <- x$decision;
                     res <-
                       data.frame(decision_id = x$decision_id,
                                  decision_label = decisionsDf[decisionsDf$id==x$decision_id, 'label'],
                                  decisions_option_value = x$decision_option_value,
                                  option_label = optionsDf[optionsDf$decision_id==x$decision_id &
                                                             optionsDf$value==x$decision_option_value, 'label'],
                                  criterion_id = x$criterion_id,
                                  criterion_label = criteriaDf[criteriaDf$id==x$criterion_id, 'label'],
                                  value = x$value,
                                  label = x$label,
                                  description = x$description,
                                  id = x$id,
                                  stringsAsFactors = FALSE);
                     return(res);
                   }));

  row.names(estimatesDf) <-
    NULL;

  res <- list(estimates_raw = estimates_raw,
              estimates = estimates,
              assertions = assertions,
              sources = sources,
              estimatesDf = estimatesDf);

  class(res) <-
    c("dmcda", "estimates");

  return(res);

}
