#' @export
load_scenarios <- function(path,
                           decisions_and_options) {

  if (!(all(c("dmcda", "decisions_and_options") %in%
            class(decisions_and_options)))) {
    stop("What you pass as 'decisions_and_options' needs to be an object as ",
         "generated by a call to the `load_decisions` function (which has ",
         "classes 'dmcda' and 'decisions_and_options', but you ",
         "passed an object of class ",
         ufs::vecTxtQ(class(decisions_and_options)), ".");
  }

  decisionsDf <-
    decisions_and_options$decisionsDf;
  optionsDf <-
    decisions_and_options$optionsDf;

  ### Use suppressWarnings because we do not need identifiers
  suppressWarnings(
    scenarios_raw <-
      justifier::load_justifications_dir(path)
  );

  ### Get all policy scenario metadata and choices
  scenariosMetadata <-
    lapply(scenarios_raw$supplemented$justifications,
           function(x) {
             if (x$type == "scenario_metadata") {
               return(x);
             } else {
               return(NULL);
             }
           });

  scenariosMetadata <-
    scenariosMetadata[!unlist(lapply(scenariosMetadata,
                                     is.null))];

  scenarioOptions <-
    lapply(scenarios_raw$supplemented$justifications,
           function(x) {
             if (x$type == "scenario_option_specification") {
               return(x);
             } else {
               return(NULL);
             }
           });

  ### Remove NULL elements
  scenarioOptions <-
    scenarioOptions[!unlist(lapply(scenarioOptions, is.null))];

  ### Convert to dataframes
  scenariosMetadataDf <-
    do.call(rbind,
            lapply(scenariosMetadata,
                   function(x) {
                     return(data.frame(scenario_id = x$scenario_id,
                                       label = x$label,
                                       description = x$description,
                                       stringsAsFactors = FALSE));
                   }));

  row.names(scenariosMetadataDf) <-
    NULL;

  scenarioOptionsDf <-
    do.call(rbind,
            lapply(scenarioOptions,
                   function(x) {
                     res <-
                       data.frame(scenario = scenariosMetadataDf[scenariosMetadataDf$scenario_id==x$scenario_id, 'label'],
                                  decision = decisionsDf[decisionsDf$id==x$decision_id, 'label'],
                                  option = optionsDf[optionsDf$decision_id==x$decision_id &
                                                       optionsDf$value==x$value, 'label'],
                                  scenario_id = x$scenario_id,
                                  decision_id = x$decision_id,
                                  decision_option_value = x$value,
                                  stringsAsFactors = FALSE);
                     names(res) <-
                       c('scenario',
                         'decision',
                         'option',
                         'scenario_id',
                         'decision_id',
                         'decision_option_value');
                     return(res);
                   }));

  row.names(scenarioOptionsDf) <-
    NULL;

  res <- list(scenarios_raw = scenarios_raw,
              scenariosMetadata = scenariosMetadata,
              scenariosMetadataDf = scenariosMetadataDf,
              scenarioOptions = scenarioOptions,
              scenarioOptionsDf = scenarioOptionsDf);

  class(res) <-
    c("dmcda", "scenarios");

  return(res);

}
