#' @export
load_weights <- function(path,
                         criteria) {

  if (!(all(c("dmcda", "criteria") %in%
            class(criteria)))) {
    stop("What you pass as 'instruments_and_options' needs to be an object as ",
         "generated by a call to the `load_outcomes` function (which has ",
         "classes 'dmcda' and 'criteria', but you ",
         "passed an object of class ",
         ufs::vecTxtQ(class(criteria)), ".");
  }

  criteriaTree <- criteria$criteriaTree;
  criteriaDf <- criteria$criteriaDf;

  ### Use suppressWarnings because we do not need identifiers
  suppressWarnings(
    weights_raw <-
      justifier::load_justifications_dir(path)
  );

  ### Get all policy instrument weights
  weights <-
    lapply(weights_raw$supplemented$justifications,
           function(x) {
             if (x$type == "criterion_weight") {
               return(x);
             } else {
               return(NULL);
             }
           });

  ### Remove NULL elements
  weights <-
    weights[!unlist(lapply(weights, is.null))];

  weightsDf <-
    do.call(rbind,
            lapply(weights,
                   function(x) {
                     res <-
                       data.frame(x$weight_profile_id,
                                  x$criterion_id,
                                  unname(criteriaDf[criteriaDf$id==x$criterion_id, 'label']),
                                  x$weight,
                                  stringsAsFactors = FALSE);
                     names(res) <-
                       c('weight_profile_id',
                         'criterion_id',
                         'criterion_label',
                         'weight');
                     return(res);
                   }));

  row.names(weightsDf) <-
    NULL;

  ### Multiply the weights

  multipliedWeights <-
    lapply(unique(weightsDf$weight_profile_id),
           function(profile) {
             res <-
               data.frame(criterion_id = weightsDf[weightsDf$weight_profile_id==profile, 'criterion_id'],
                          multipliedWeight = unlist(lapply(weightsDf[weightsDf$weight_profile_id==profile, 'criterion_id'],
                                                           function(id) {
                                                             idList <- data.tree::FindNode(criteriaTree,
                                                                                           id)$Get("id",
                                                                                                   traversal="ancestor");
                                                             return(prod(weightsDf[weightsDf$weight_profile_id==profile &
                                                                                     weightsDf$outcome_id %in% idList, 'weight']));
                                                           })));
             res$profile_id <-
               rep(profile,
                   nrow(res));
             return(res);
           });

  multipliedWeights <-
    do.call(rbind,
            multipliedWeights);

  res <- list(weights_raw = weights_raw,
              weights = weights,
              weightsDf = weightsDf,
              multipliedWeights = multipliedWeights);

  class(res) <-
    c("dmcda", "weights");

  return(res);

}
